name: "valgrade"
version: "1.0.2"
usage: "upgrade values while preserving custom changes"
description: |-
  This plugin helps upgrade Helm chart values files by carrying over
  changes made to the base values file to the new version of the values file.
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/bin/helm-valgrade"
hooks:
  install: "$HELM_PLUGIN_DIR/install-plugin.sh"
  update: "$HELM_PLUGIN_DIR/install-plugin.sh"
