name: ci

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup-go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.6"

      - name: install-deps
        run: make deps

      - name: run-tests
        run: make test

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup-go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.6"

      - name: install-lint
        run: make install-lint

      - name: run-lint
        run: make lint

  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - uses: actions/checkout@v3

      - name: setup-go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.6"

      - name: build-linux
        run: make build-linux

      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: helm-valgrade-linux
          path: helm-valgrade_unix
